### ISSUE TITLE
Bug: Running test command throws error

### ISSUE THREAD

**Issue by annibuliful** [keenlycode/adapter#25]
<img width="705" alt="Screenshot 2567-01-02 at 00 28 14" src="https://github.com/keenlycode/adapter/assets/5283709/1c6a3f96-8c65-4533-85ec-7ed5fd876a8d">

I'm no a big fan of python `venv` so I have no idea what to do

**Comment by nitipit** [comment]
For testing, now I'm using web browser engine to test directly which you can see the result on this page -> https://keenlycode.github.io/adapter/test/

I've used **Jest** Before but it lacks some features about `CSSStyleSheets` and `document.adoptedstylesheets` (and not yet about Shadow DOM), so I switch to generate html/js and test it directly on browser engine because it will support `document.adoptedstylesheets` and `getcomputedstyle` which I think it's the best option to test dynamic styling.

My ideal is to switch completely to JS but I lack skill of using Static HTML Generators with customization in javascript, so I just use python 😂. Any suggestion ? Thanks

**Comment by annibuliful** [comment]
I'm OK with it to move JS

**Comment by nitipit** [comment]
Done at commit: 306c097692cd88b5565ffd1383fd9557fb2df850
`npm run test` now can be used in javascript only environment
